version: '3'
services:
  nextjs:
    build: ./
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/sample-app/
    ports:
      - '3000:3000'
    command: 'npm run dev'
